"""empty message

Revision ID: 83e239550ae5
Revises: 
Create Date: 2022-06-25 16:38:02.735274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e239550ae5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysadmins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=10), nullable=True),
    sa.Column('lastName', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('sysadmin_id', sa.Integer(), nullable=True),
    sa.Column('external_ip', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['sysadmin_id'], ['sysadmins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypervisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('ilo_ip_address', sa.String(length=15), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=15), nullable=True),
    sa.Column('server_ip', sa.String(length=15), nullable=True),
    sa.Column('server_os', sa.String(length=15), nullable=True),
    sa.Column('nrpe_port', sa.String(length=15), nullable=True),
    sa.Column('hypervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hypervisor_id'], ['hypervisor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    op.drop_table('hypervisor')
    op.drop_table('sites')
    op.drop_table('sysadmins')
    # ### end Alembic commands ###
